name: Next.js CI
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "devops_next/**"
      
jobs:
  build-next-app:
    name: Build Next.js App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops_next
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
      - name: Build Docker image
        working-directory: ./devops_next
        run: |
          docker build -t next-app:latest .
      
      