name: gane validation pipeline
on:
  pull_request:
    types: [closed, synchronize, opened]
    branches:
      - main
    paths:
        - "TestProj/**"
      
jobs:
  build-unity-app:
    name: Build Unity App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TestProj
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
    
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
        
          